apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-application
  name: product-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-application
  strategy: {}
  template:
    metadata:

      labels:
        app: product-application
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: saiupadhyayula007/product-application:latest
          name: product-application
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-application
  name: product-application
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 9194
  selector:
    app: product-application
status:
  loadBalancer: {}
