apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-application
  name: notification-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-application
  strategy: {}
  template:
    metadata:
      labels:
        app: notification-application
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: saiupadhyayula007/notification-application:latest
          name: notification-application
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-application
  name: notification-application
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 9192
  selector:
    app: notification-application
status:
  loadBalancer: {}
